# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
