# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_users_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='Admins',
        ),
    ]
